name: Node.js Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: Ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        package:
          - '@json2csv/formatters'
          - '@json2csv/transforms'
          - '@json2csv/plainjs'
          - '@json2csv/whatwg'
          - '@json2csv/node'
          - '@json2csv/cli'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public -w ${{ matrix.package }}
